country = "Ägypten"
last_name = "shahin"

#residence_option = "//p[contains(.,'Aufenthaltstitel - beantragen')]"
#group_option = "//p[contains(.,'Studium und Ausbildung')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine Berufsausbildung (§ 16a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine betriebliche Weiterbildung (§ 16a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Besuch eines Sprachkurses (§ 16f Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Schulbesuch oder zur Teilnahme an einem Schüleraustausch (§ 16f)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Studium (§ 16b)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Anerkennung einer ausländischen Berufs-Qualifikation im Rahmen einer Qualifizierungsmaßnahme (§ 16d Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Anerkennung einer ausländischen Berufs-Qualifikation in einem nicht reglementierten Beruf (§ 16d Abs. 3)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Aufnahme eines Praktikums (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Studienvorbereitung (§ 16b Abs. 1)')]"

#group_option = "//p[contains(.,'Erwerbstätigkeit')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für die Teilnahme an einem Freiwilligendienst (§§ 19c oder 19e)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine qualifizierte Beschäftigung in der Informations- und Kommunikationstechnologie (§19c Abs. 2)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte mit akademischer Ausbildung (§ 18b Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte mit Berufsausbildung (§ 18a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte zur Arbeitsplatzsuche - Erteilung (§ 20)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für in anderen EU-Staaten langfristig Aufenthaltsberechtigte (§ 38a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für wissenschaftliche Mitarbeiter und Forscher (§ 18d)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Aufnahme eines Praktikums (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Beschäftigung als Au-pair (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur freiberuflichen Tätigkeit - Erteilung (§ 21 Abs. 5)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur selbstständigen Tätigkeit - Erteilung (§ 21)')]"
#reason_option = "//label[contains(.,'Blaue Karte EU (§ 18b Abs. 2)')]"

#group_option = "//p[contains(.,'Familiäre Gründe')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für ein neugeborenes Kind - Erteilung (§ 33)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner und Kinder von Fachkräften, Studierenden, Auszubildenden, Wissenschaftlern und Lehrkräften (§§ 29-32)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner und Kinder von Inhabern einer Blauen Karte EU (§§ 29-32)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von ausländischen Familienangehörigen (§§ 29-34)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von deutschen Familienangehörigen (§ 28)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von subsidiär Schutzberechtigten (§ 36a)')]"

#group_option = "//p[contains(.,'Besondere Aufenthaltsrechte')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für in anderen EU-Staaten langfristig Aufenthaltsberechtigte (§ 38a)')]"

residence_option = "//p[contains(.,'Aufenthaltstitel - verlängern')]"
group_option = "//p[contains(.,'Studium und Ausbildung')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine Berufsausbildung (§ 16a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine betriebliche Weiterbildung (§ 16a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Besuch eines Sprachkurses (§ 16f Abs. 1)')]"
reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Schulbesuch oder zur Teilnahme an einem Schüleraustausch (§ 16f)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zum Studium (§ 16b)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Anerkennung einer ausländischen Berufs-Qualifikation im Rahmen einer Qualifizierungsmaßnahme (§ 16d Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Anerkennung einer ausländischen Berufs-Qualifikation in einem nicht reglementierten Beruf (§ 16d Abs. 3)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Aufnahme eines Praktikums (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Studienvorbereitung (§ 16b Abs. 1)')]"

#group_option = "//p[contains(.,'Erwerbstätigkeit')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für eine qualifizierte Beschäftigung in der Informations- und Kommunikationstechnologie (§19c Abs. 2)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte mit akademischer Ausbildung (§ 18b Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte mit Berufsausbildung (§ 18a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Fachkräfte zur Arbeitsplatzsuche - Erteilung (§ 20)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für in anderen EU-Staaten langfristig Aufenthaltsberechtigte (§ 38a)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für wissenschaftliche Mitarbeiter und Forscher (§ 18d)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Aufnahme eines Praktikums (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur Beschäftigung als Au-pair (§ 19c Abs. 1)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis zur selbstständigen oder freiberuflichen Tätigkeit - Verlängerung (§ 21)')]"
#reason_option = "//label[contains(.,'Blaue Karte EU (§ 18b Abs. 2)')]"

#group_option = "//p[contains(.,'Familiäre Gründe')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner und Kinder von Fachkräften, Studierenden, Auszubildenden, Wissenschaftlern und Lehrkräften (§§ 29-32)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner und Kinder von Inhabern einer Blauen Karte EU (§§ 29-32)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von ausländischen Familienangehörigen (§§ 29-34)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von deutschen Familienangehörigen (§ 28)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für Ehepartner, Eltern und Kinder von subsidiär Schutzberechtigten (§ 36a)')]"

#group_option = "//p[contains(.,'Humanitäre Gründe')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis aus humanitären Gründen - Verlängerung (§§ 22 - 25)')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis in Härtefällen - Verlängerung (§ 23a)')]"

#group_option = "//p[contains(.,'Besondere Aufenthaltsrechte')]"
#reason_option = "//label[contains(.,'Aufenthaltserlaubnis für in anderen EU-Staaten langfristig Aufenthaltsberechtigte (§ 38a)')]"

#residence_option = "//p[contains(.,'Aufenthaltstitel in einen neuen Pass übertragen')]"
#reason_option = "//label[contains(.,'Übertragen einer Aufenthaltserlaubnis auf einen neuen Pass')]"
#reason_option = "//label[contains(.,'Übertragen einer Blauen Karte EU auf einen neuen Pass')]"
#reason_option = "//label[contains(.,'Übertragen einer Niederlassungserlaubnis oder Erlaubnis zum Daueraufenthalt-EU auf einen neuen Pass')]"
#reason_option = "//label[contains(.,'Übertragen eines Aufenthaltsdokument-GB auf einen neuen Pass')]"

#residence_option = "//p[contains(.,'Niederlassungserlaubnis beantragen')]"
#reason_option = "//label[contains(.,'Niederlassungserlaubnis für Familienangehörige von Deutschen (§ 28 Abs. 2)')]"
#reason_option = "//label[contains(.,'Niederlassungserlaubnis für Kinder - Erteilung (§ 35)')]"

#residence_option = "//p[contains(.,' Aufenthaltsgestattung (Asyl) - verlängern')]"
#reason_option = "//label[contains(.,'Aufenthaltsgestattung - verlängern')]"

#residence_option = "//p[contains(.,'Duldung - verlängern')]"
#reason_option = "//label[contains(.,'Duldung - verlängern')]"


